### ISSUE TITLE
Problem running the funnel macro

### ISSUE THREAD

**Issue by fivetran-reneeli** [mjirv/dbt_product_analytics#6]
https://github.com/mjirv/dbt_product_analytics/blob/ed8a3202323c43d41b120448ea804ff0a159ca1e/macros/funnel.sql#L39

Hi, I'm getting this error trying to run the funnel macro using bigquery. I'm assuming it has to do with the line above. Thanks!

` Window ORDER BY is required for analytic function first_value at [126:81]`

**Comment by mjirv** [comment]
Hey @fivetran-reneeli. Sorry for the delay here! I swear sometimes GitHub emails me when issues are opened and sometimes it just doesn't...

Anyway, I'm looking into this now!

**Comment by mjirv** [comment]
Hi @fivetran-reneeli this should be fixed in version 0.3.1 which will be available on dbt Package Hub in the next hour or so.

Can you please confirm whether it's working for you when you have a chance? Thanks for bringing this to my attention!

**Comment by fivetran-reneeli** [comment]
Hi @mjirv awesome, just re-ran and it works perfectly!
